language: haskell

env:
  - GHCVER=7.8.4 STACK_YAML=stack-7.8.yaml
  - GHCVER=7.10.2 STACK_YAML=stack.yaml

branches:
  only:
    - master

sudo: false

cache:
  directories:
    - $HOME/.stack/

before_install:
  - mkdir -p $HOME/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  #- export STACK_VERSION=0.1.6.0
  #- export STACK_FULLVERSION=stack-$STACK_VERSION-linux-x86_64
  #- travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v$STACK_VERSION/$STACK_FULLVERSION.tar.gz | tar -xz -C /tmp $STACK_FULLVERSION/stack
  #- mv /tmp/$STACK_FULLVERSION/stack $HOME/.local/bin
  - travis_retry curl -L https://github.com/rubik/argon/releases/download/test-stack-1.7/stack-linux-x64.tar.bz2 | tar -xj -C $HOME/.local/bin
  - chmod a+x $HOME/.local/bin/stack
  - stack --version

install:
  - stack setup --no-terminal

script:
  - stack test :argon-test --no-terminal --coverage

after_script:
  - travis_retry curl -L https://github.com/rubik/stack-hpc-coveralls/releases/download/v0.0.1.0/shc-linux-x64-$GHCVER.tar.bz2 | tar -xj
  - ./shc argon argon-test
